project:
  type: website

website:
  title: "Phillipa Gowdy-Jaehnig"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - projects.qmd
      - contact.qmd
      
page-footer:
  left: "Phillipa Gowdy-Jaehnig"

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true