project:
  type: website

website:
  title: "Phillipa Gowdy-Jaehnig"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        about.qmd
      - text: "Projects"
        projects.qmd
      - text: "Contact"
        contact.qmd
      
page-footer:
  left: "Phillipa Gowdy-Jaehnig"

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true